pipeline:
  integration-test:
    image: "attxproject/dockerize-drone-test:dev"
    commands:
      - "dockerize -wait tcp://mysql:3306 -timeout 240s"
      - "dockerize -wait http://fuseki:3030 -timeout 60s"
      - "dockerize -wait http://graphmanager:4302/health -timeout 60s"
      - "dockerize -wait http://es5:9210 -timeout 60s"

services:
  mysql:
    image: "attxproject/unified-views-mariadb:stable-1.2"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  fuseki:
    image: "attxproject/attx-fuseki:dev"
    environment:
      - ADMIN_PASSWORD=pw123
  graphmanager:
    image: "attxproject/gm-api:dev"
  es5:
    image: "attxproject/attx-es5:1.0"
