pipeline: 
  dockerize: 
    commands: 
      - "dockerize -wait tcp://mysql:3306 -timeout 240s"
    group: test
    image: "attxproject/dockerize-drone-test:dev"
  mysql: 
    group: test
    mysql: 
      environment: 
        - MYSQL_ROOT_PASSWORD=iamroot!
      image: "attxproject/unified-views-mariadb:stable-1.2"
      ports: 
        - "3306:3306"
