pipeline:
  integration-test:
    image: "attxproject/dockerize-drone-test:dev"
    dockerize: 
      commands: 
        - "dockerize -wait tcp://mysql:3306 -timeout 240s"
      
      
services:
  mysql:
    image: "attxproject/unified-views-mariadb:stable-1.2"
    environment: 
      - MYSQL_ROOT_PASSWORD=iamroot!
    ports: 
      - "3306:3306"
