pipeline:
  integration-test:
    image: "attxproject/integrationtests:dev"
    environment:
      - BASE=pdTest
    commands:
      - "/tmp/runTests.sh"
      
services:
  messagebroker:
    image: "rabbitmq:3.6.11-management"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
         
  rmlservice:
    image: "attxproject/rml-service:dev"
    environment:
      - MHOST=amqp://messagebroker
      - MUSER=user
      - MPASS=password
      - MEXCHANGE=
      - MQUEUE=rmlservice
