pipeline:
  integration-test:
    image: "attxproject/dockerize-drone-test:dev"
    commands:
      - "dockerize -wait tcp://mysql:3306 -timeout 240s"
      - "dockerize -wait http://fuseki:3030 -timeout 60s"
      - "dockerize -wait http://graphmanager:4302/health -timeout 60s"
      - "dockerize -wait http://uvprov:4301/health -timeout 60s"
      - "dockerize -wait http://provservice:7030/health -timeout 60s"

services:
  mysql:
    image: "attxproject/unified-views-mariadb:stable-1.2"
    environment:
       - MYSQL_ROOT_PASSWORD=iamroot!
  fuseki:
    image: "attxproject/attx-fuseki:dev"
    environment:
      - ADMIN_PASSWORD=pw123
  messagebroker:
    image: "rabbitmq:3.6.11-management"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  graphmanager:
    image: "attxproject/gm-api:dev"
  uvprov:
    image: "attxproject/uv-prov:dev"
  provservice:
    image: "attxproject/provenance-service:dev"
